version: '3.5'

services:

  ui:
    container_name: lnhw-ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    volumes:
      - '.:/usr/src/ui'
      - '/usr/src/ui/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

  rpc:
    container_name: lnhw-rpc
    build:
      context: .
      dockerfile: ./rpc/Dockerfile
    volumes:
      - '.:/usr/src/rpc'
    ports:
      - '5000:5000'
